import DashboardHeadLine from '@/components/dashboard/dashboardHeadLine/DashboardHeadLine';
import DashboardTableOrders from '@/components/dashboard/dashboardTableOrders/DashboardTableOrders';

import styles from './styles.module.scss';

const data = [
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
	{
		id: '#31533',
		product: 'Science Fiction Book',
		category: 'Books',
		date: '08.08.24',
		status: 'Received',
		quantity: '2pcs',
		price: '$120',
	},
];

export default function DashboardProducts() {
	return (
		<div className={styles.wrapper}>
			<DashboardHeadLine compact={true} text={'Orders'} />
			<DashboardTableOrders data={data} />
		</div>
	);
}
