import type { Metadata } from 'next';

import Container from '@/components/Container/Container';
import DashboardFooter from '@/components/dashboard/DashboardFooter/DashboardFooter';
import DashboardSidebar from '@/components/dashboard/DashboardSidebar/DashboardSidebar';
import DashboardHeader from '@/components/DashboardHeader/DashboardHeader';
import { londrinaSolid } from '@/styles/fonts/fonts';

import '@/styles/reset.scss';
import '@/styles/variables.scss';
import '@/styles/globals.scss';

import styles from './page.module.scss';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function DashboardLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className={londrinaSolid.className}>
				<div className={styles.bodyInner}>
					<DashboardHeader />
					<Container className={styles.container}>
						<main className={styles.main}>
							<DashboardSidebar />
							<div className={styles.wrapper}>{children}</div>
						</main>
						<DashboardFooter />
					</Container>
				</div>
			</body>
		</html>
	);
}
